// src/components/layout/navbar.svelte
<div class="w-full bg-fg border-b-2 border-line h-24 static flex flex-row items-center z-10">
    <img src="logo.png" class="aspect-square h-12 lg:h-20 border-solid border-2 border-white rounded-3xl lg:ml-24"/>
    <span class="font-extrabold ml-2 text-2xl">WalterCraft</span>
    <!--
    <div class="h-full flex items-center justify-center ml-5">
        <a class="text-[#ACACAC] text-xl">Галерея</a>
    </div>
    <div class="h-full flex items-center justify-center ml-10">
        <a class="text-[#ACACAC] text-xl">FAQ</a>
    </div>
    <div class="h-full flex items-center justify-center ml-10">
        <a class="text-[#ACACAC] text-xl">Блог</a>
    </div>
    -->
</div>

// components/Fragments/Navbar.tsx

export default function Navbar() {
    return (
        <div className="w-full bg-fg border-b-2 border-line h-24 static flex flex-row">
            <img src="logo.png" className="aspect-square w-24 border-solid border-2 border-white rounded-2xl relative top-5 ml-32"/>
            <div className="h-full flex items-center justify-center ml-5">
                <a className="text-[#ACACAC] text-2xl">Галерея</a>
            </div>
            <div className="h-full flex items-center justify-center ml-10">
                <a className="text-[#ACACAC] text-2xl">FAQ</a>
            </div>
            <div className="h-full flex items-center justify-center ml-10">
                <a className="text-[#ACACAC] text-2xl">Блог</a>
            </div>
        </div>
    )
}
