// components/Fragments/Footer.tsx
export default function Footer() {
    return (
        <div className="w-full bg-fg border-t-2 border-line flex flex-row">
            <div className="flex flex-col">
                <div className="flex flex-row items-center">
                    <img src="logo.png" className="aspect-square w-24 border-solid border-2 border-white rounded-2xl ml-32"/>
                    <span className="text-3xl font-bold text-white">WalterCraft</span>
                    <img src="github.png" className="aspect-auto h-9" />
                    <img src="discord.png" className="aspect-auto h-9" />
                </div>
            </div>
        </div>
    )
}

// src/components/layout/footer.svelte
<script>
    import {footerEN, footerRU} from "$lib/constants"
</script>

<div class="w-full bg-fg border-t-2 border-line flex flex-row h-fit">
    <div class="flex flex-col lg:ml-32 items-start">
        <div class="flex flex-col lg:flex-row lg:items-center mt-5">
            <div class="flex flex-row items-center">
                <img src="logo.png" alt="WalterCraft" class="aspect-square w-12 lg:w-24 border-solid border-2 border-white rounded-2xl"/>
                <span class="text-2xl lg:text-3xl h-fit font-bold text-white ml-2">WalterCraft</span>
            </div>
            <div class="flex flex-row mt-2">
                <!--
                <img src="github.png" class="aspect-auto h-9 w-9 lg:ml-5" />
                <img src="discord.png" class="aspect-auto h-9 w-12 ml-2 lg:ml-5" />
                -->
            </div>
        </div>

        <p class="lg:w-96 h-fit mt-2 text-[#95969E]">
            {footerRU}
        </p>

        <p class="lg:w-96 h-fit mt-4 text-[#95969E]">
            {footerEN}
        </p>
    </div>
</div>
